openapi: 3.0.0
info:
  title: VEDO
  description: API for VEDO
  version: 1.0.0
paths:
  /authorization:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /registration:
    post:
      summary: Registration user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        '200':
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /jobTitle:
    get:
      summary: Get job titles
      responses:
        '200':
          description: job titles successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobTitlesResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /branches:
    get:
      summary: Get branches
      responses:
        '200':
          description: branches successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BranchesListResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /branch-settings:
    get:
      summary: Get signers of branch
      parameters:
        - name: branchId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: signers successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BranchSettingsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /branch-codes:
    get:
      summary: Get codes branch
      responses:
        '200':
          description: branches successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BranchCodeListResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /doc-types:
    get:
      summary: Get doc types
      responses:
        '200':
          description: doc types successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocTypeListResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /doc-info:
    get:
      summary: Get a doc info
      parameters:
        - name: docId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: docInfo successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocInfoResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /docs:
    get:
      summary: Get docs
      parameters:
        - name: docId
          in: query
          required: true
          schema:
            type: integer
        - name: branchId
          in: query
          required: true
          schema:
            type: integer
        - name: dateStart
          in: query
          required: true
          schema:
            type: string
        - name: dateEnd
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: docs successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
  /chains:
    get:
      summary: Get chains
      parameters:
        - name: branchId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: chains successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChainsResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    LoginRequest:
      type: object
      required:
        - user
        - password
      additionalProperties: false
      properties:
        user:
          type: string
          format: email
        password:
          type: string
          format: password
    LoginResponse:
      type: object
      required:
        - accessToken
      additionalProperties: false
      properties:
        accessToken:
          type: string
    Error:
      type: object
      required:
        - message
        - code
      additionalProperties: false
      properties:
        message:
          type: string
        code:
          type: string
    RegistrationRequest:
      type: object
      required:
        - lastName
        - firstName
        - jobTitle
        - code1C
        - email
        - pinCode
      additionalProperties: false
      properties:
        lastName:
          type: string
          description: Фамилия
        firstName:
          type: string
          description: Имя
        middleName:
          type: string
          description: Отчество (необязательно)
        jobTitle:
          type: string
          description: Должность
        code1C:
          type: string
          description: Код 1С
        email:
          type: string
          format: email
          description: Электронная почта
        pinCode:
          type: string
          description: Пин-код
        codeSm:
          type: string
          description: Код SM (необязательно)
        codeSymphony:
          type: string
          description: Код Symphony (необязательно)
        codeTcd:
          type: string
          description: Код TCD (необязательно)
        codeInfor:
          type: string
          description: Код Infor (необязательно)
        codeDax:
          type: string
          description: Код DAX (необязательно)
    RegistrationResponse:
      type: object
      required:
        - code
        - message
      additionalProperties: false
      properties:
        code:
          type: string
        message:
          type: string
    JobTitleItem:
      type: object
      required:
        - id
        - jobTitle
      properties:
        id:
          type: integer
        jobTitle:
          type: string
    JobTitlesResponse:
      type: object
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/JobTitleItem'
    BranchItem:
      type: object
      required:
        - id
        - branch
      properties:
        id:
          type: integer
        branch:
          type: string
    BranchesListResponse:
      type: object
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/BranchItem'
    DocTypesItem:
      type: object
      required:
        - docId
        - checked
      properties:
        docId:
          type: integer
        checked:
          type: boolean
    Signer:
      type: object
      required:
        - row
        - jobTitleId
        - email
        - docTypes
      properties:
        row:
          type: integer
        jobTitleId:
          type: integer
        email:
          type: string
        docTypes:
          type: array
          items:
            $ref: '#/components/schemas/DocTypesItem'
    Setting:
      type: object
      required:
        - row
        - typeId
        - code
      properties:
        row:
          type: integer
        typeId:
          type: integer
        code:
          type: string
    BranchSettingsResponse:
      type: object
      required:
        - signers
        - settings
      additionalProperties: false
      properties:
        signers:
          type: array
          items:
            $ref: '#/components/schemas/Signer'
        settings:
          type: array
          items:
            $ref: '#/components/schemas/Setting'
    BranchCodeItem:
      type: object
      required:
        - id
        - code
      properties:
        id:
          type: integer
        code:
          type: string
    BranchCodeListResponse:
      type: object
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/BranchCodeItem'
    DocTypeItem:
      type: object
      required:
        - id
        - docType
      properties:
        id:
          type: integer
        docType:
          type: string
    DocTypeListResponse:
      type: object
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/DocTypeItem'
    DocInfoItem:
      type: object
      required:
        - question
        - answer
      properties:
        question:
          type: string
        answer:
          type: string
    DocInfoResponse:
      type: object
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/DocInfoItem'
    DocsItem:
      type: object
      required:
        - docName
        - date
        - approved
      properties:
        docName:
          type: string
        date:
          type: string
        approved:
          type: boolean
    DocsResponse:
      type: object
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/DocsItem'
    ApproverItem:
      type: object
      required:
        - queueId
        - jobTitleId
        - email
      properties:
        queueId:
          type: integer
        jobTitleId:
          type: integer
        email:
          type: string
    ChainsItem:
      type: object
      required:
        - docType
        - docSource
        - approvers
      properties:
        docType:
          type: string
        docSource:
          type: string
        approvers:
          type: array
          items:
            $ref: '#/components/schemas/ApproverItem'
    ChainsResponse:
      type: object
      required:
        - list
      additionalProperties: false
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/ChainsItem'
  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
