schemas:
  Signer:
    type: object
    required:
      - row
      - signer
      - email
      - docTypes
    properties:
      row:
        type: integer
      signer:
        type: string
      email:
        type: string
      docTypes:
        type: array
        items:
          type: object
          required:
            - doc
            - checked
          properties:
            doc:
              type: string
            checked:
              type: boolean
          
  Setting:
    type: object
    required:
      - row
      - type
      - code
    properties:
      row:
        type: integer
      type:
        type: string
      code:
        type: string
  BranchSettingsResponse:
    type: object
    required:
      - signers
      - settings
    additionalProperties: false
    properties:
      signers:
        type: array
        items:
          $ref: '#/schemas/Signer'
      settings:
        type: array
        items:
          $ref: '#/schemas/Setting'

branchSettings:
  summary: Get signers of branch
  parameters:
    - name: branch
      in: query
      required: true
      schema:
        type: string
  responses:
    "200":
      description: signers successful
      content:
        application/json:
          schema:
            $ref: "#/schemas/BranchSettingsResponse"
    "401":
      $ref: "../shared/responses.yaml#/UnauthorizedError"
    "404":
      $ref: "../shared/responses.yaml#/NotFoundError"