schemas:
  DocTypesItem:
    type: object
    required:
      - docId
      - checked
    properties:
      docId:
        type: integer
      checked:
        type: boolean
  Signer:
    type: object
    required:
      - row
      - jobTitleId
      - email
      - docTypes
    properties:
      row:
        type: integer
      jobTitleId:
        type: [integer, "null"]
      email:
        type: string
      docTypes:
        type: array
        items:
          $ref: '#/schemas/DocTypesItem'
  Setting:
    type: object
    required:
      - row
      - typeId
      - code
    properties:
      row:
        type: integer
      typeId:
        type: [integer, "null"]
      code:
        type: string

  BranchSignersResponse:
    type: object
    required:
      - signers
    additionalProperties: false
    properties:
      signers:
        type: array
        items:
          $ref: '#/schemas/Signer'
  BranchSettingsResponse:
    type: object
    required:
      - settings
    additionalProperties: false
    properties:
      settings:
        type: array
        items:
          $ref: '#/schemas/Setting'

  UpdateBranchSignersRequest:
    type: object
    required:
      - branchId
      - signers
    additionalProperties: false
    properties:
      branchId:
        type: integer
      signers:
        type: array
        items:
          $ref: '#/schemas/Signer'
  UpdateBranchSettingsRequest:
    type: object
    required:
      - branchId
      - settings
    additionalProperties: false
    properties:
      branchId:
        type: integer
      settings:
        type: array
        items:
          $ref: '#/schemas/Setting'

  UpdateBranchResponse:
    type: object
    required:
      - code
      - message
    additionalProperties: false
    properties:
      code:
        type: string
      message:
        type: string

branchSigners:
  summary: Get signers of branch
  parameters:
    - name: branchId
      in: query
      required: true
      schema:
        type: integer
  responses:
    "200":
      description: signers successful
      content:
        application/json:
          schema:
            $ref: "#/schemas/BranchSignersResponse"
    "401":
      $ref: "../shared/responses.yaml#/UnauthorizedError"
    "404":
      $ref: "../shared/responses.yaml#/NotFoundError"
branchSettings:
  summary: Get settings of branch
  parameters:
    - name: branchId
      in: query
      required: true
      schema:
        type: integer
  responses:
    "200":
      description: settings successful
      content:
        application/json:
          schema:
            $ref: "#/schemas/BranchSettingsResponse"
    "401":
      $ref: "../shared/responses.yaml#/UnauthorizedError"
    "404":
      $ref: "../shared/responses.yaml#/NotFoundError"

updateBranchSigners:
  summary: Update signers of branch
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "#/schemas/UpdateBranchSignersRequest"
  responses:
    "200":
      description: Update signers successful
      content:
        application/json:
          schema:
            $ref: "#/schemas/UpdateBranchResponse"
    "401":
      $ref: "../shared/responses.yaml#/UnauthorizedError"
updateBranchSettings:
  summary: Update settings of branch
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "#/schemas/UpdateBranchSettingsRequest"
  responses:
    "200":
      description: Update settings successful
      content:
        application/json:
          schema:
            $ref: "#/schemas/UpdateBranchResponse"
    "401":
      $ref: "../shared/responses.yaml#/UnauthorizedError"