schemas:
  Signer:
    type: object
    required:
      - row
      - jobTitleId
      - email
      - docTypesId
    properties:
      row:
        type: integer
      jobTitleId:
        type: integer
      email:
        type: string
      docTypesId:
        type: array
        items:
          type: object
          required:
            - docId
            - checked
          properties:
            docId:
              type: integer
            checked:
              type: boolean
          
  Setting:
    type: object
    required:
      - row
      - typeId
      - code
    properties:
      row:
        type: integer
      typeId:
        type: integer
      code:
        type: string
  BranchSettingsResponse:
    type: object
    required:
      - signers
      - settings
    additionalProperties: false
    properties:
      signers:
        type: array
        items:
          $ref: '#/schemas/Signer'
      settings:
        type: array
        items:
          $ref: '#/schemas/Setting'

branchSettings:
  summary: Get signers of branch
  parameters:
    - name: branchId
      in: query
      required: true
      schema:
        type: integer
  responses:
    "200":
      description: signers successful
      content:
        application/json:
          schema:
            $ref: "#/schemas/BranchSettingsResponse"
    "401":
      $ref: "../shared/responses.yaml#/UnauthorizedError"
    "404":
      $ref: "../shared/responses.yaml#/NotFoundError"