openapi: 3.0.0
info:
  title: VEDO
  description: API for VEDO
  version: 1.0.0
paths:
  /authorization:
    post:
      $ref: "./endpoints/auth.yaml#/authorization"
  /registration:
    post:
      $ref: "./endpoints/registrationUser.yaml#/registrationUser"  
  /jobTitle:
    get:
      $ref: "./endpoints/jobTitles.yaml#/jobTitles"
  /branches:
    get:
      $ref: "./endpoints/branches.yaml#/branches"

  /branch-signers:
    get:
      $ref: "./endpoints/branchSettings.yaml#/branchSigners"
  /branch-settings:
    get:
      $ref: "./endpoints/branchSettings.yaml#/branchSettings"
  /update-branch-signers:
    put:
      $ref: "./endpoints/branchSettings.yaml#/updateBranchSigners"
  /update-branch-settings:
    put:
      $ref: "./endpoints/branchSettings.yaml#/updateBranchSettings"
  
  /branch-codes:
    get:
      $ref: "./endpoints/branchCodes.yaml#/branchCodes"
  /doc-types:
    get:
      $ref: "./endpoints/docTypes.yaml#/docTypes"
  /doc-info:
    get:
      $ref: "./endpoints/docInfo.yaml#/docInfo"
  /docs:
    get:
      $ref: "./endpoints/docs.yaml#/docs"
  /chains:
    get:
      $ref: "./endpoints/chains.yaml#/chains"
  /regular-approvers:
    get:
      $ref: "./endpoints/regularApprovers.yaml#/regularApprovers"

  /create-regular-approver:
    post:
      $ref: "./endpoints/regularApprovers.yaml#/createRegularApprover"  