openapi: 3.0.0
info:
  title: VEDO
  description: API for VEDO
  version: 1.0.0
paths:
  /authorization:
    post:
      $ref: "./endpoints/auth.yaml#/authorization"
  /registration:
    post:
      $ref: "./endpoints/registrationUser.yaml#/registrationUser"  
  /jobTitles:
    post:
      $ref: "./endpoints/jobTitles.yaml#/jobTitles"